### ISSUE TITLE
Installation overwrites existing .gdbinit

### ISSUE THREAD

**Issue by hdarjus** [dmillard/eigengdb#2]
I blindly executed your script and now I have to redo all my gdb initialization setup because your script overwrote my existing .gdbinit. Please, for others' sake, update the description and include a warning about this. Thank you.

**Comment by dmillard** [comment]
Hi @hdarjus, thanks for the warning. In commit d7c9b01cb7b2ac8e2b8ed10c3219bc1e54cd850e I've fixed the script to append instead of overwrite the existing `.gdbinit` file.
